// SPDX-FileCopyrightText: 2020 David Fong
// SPDX-License-Identifier: AGPL-3.0-or-later
#ifndef HPP_OKIIDOKU_DETAIL_ORDER_TEMPLATES_MACROS
#define HPP_OKIIDOKU_DETAIL_ORDER_TEMPLATES_MACROS

#include <okiidoku/config/defaults.hpp>


#if OKIIDOKU_OPTION_SUPPORT_O2
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O2 OKIIDOKU_FOREACH_O_EMIT(2u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O2
#endif

#if OKIIDOKU_OPTION_SUPPORT_O3
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O3 OKIIDOKU_FOREACH_O_EMIT(3u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O3
#endif

#if OKIIDOKU_OPTION_SUPPORT_O4
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O4 OKIIDOKU_FOREACH_O_EMIT(4u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O4
#endif

#if OKIIDOKU_OPTION_SUPPORT_O5
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O5 OKIIDOKU_FOREACH_O_EMIT(5u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O5
#endif

#if OKIIDOKU_OPTION_SUPPORT_O6
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O6 OKIIDOKU_FOREACH_O_EMIT(6u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O6
#endif

#if OKIIDOKU_OPTION_SUPPORT_O7
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O7 OKIIDOKU_FOREACH_O_EMIT(7u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O7
#endif

#if OKIIDOKU_OPTION_SUPPORT_O8
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O8 OKIIDOKU_FOREACH_O_EMIT(8u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O8
#endif

#if OKIIDOKU_OPTION_SUPPORT_O9
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O9 OKIIDOKU_FOREACH_O_EMIT(9u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O9
#endif

#if OKIIDOKU_OPTION_SUPPORT_O10
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O10 OKIIDOKU_FOREACH_O_EMIT(10u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O10
#endif

#if OKIIDOKU_OPTION_SUPPORT_O11
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O11 OKIIDOKU_FOREACH_O_EMIT(11u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O11
#endif

#if OKIIDOKU_OPTION_SUPPORT_O12
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O12 OKIIDOKU_FOREACH_O_EMIT(12u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O12
#endif

#if OKIIDOKU_OPTION_SUPPORT_O16
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O16 OKIIDOKU_FOREACH_O_EMIT(16u)
#else
#define OKIIDOKU_DETAIL_TEMPLATE_FOR_O16
#endif


/** emits `OKIIDOKU_FOREACH_O_EMIT(O)` for each `O` chosen to be compiled.

at usage sites, first `#define OKIIDOKU_FOREACH_O_EMIT` and then `#undef` it right after.
\internal This _seems_ to violate pitchfork library spec:
	"A library should not offer the user controls for tweaking its public interface."...
	https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs#libraries
	But I think it's okay. Each order could be technically be treated as its own standalone API. */
#define OKIIDOKU_FOREACH_O_DO_EMIT \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O2 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O3 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O4 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O5 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O6 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O7 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O8 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O9 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O10 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O11 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O12 \
OKIIDOKU_DETAIL_TEMPLATE_FOR_O16

#endif