#!/bin/sh
# I apologize for committing the platform-specific sed filter.
# I want to keep this script in the repo so please bear with it
# as a viewer and fellow programmer :)
#
# Personal notes:
# https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
set -e
readonly CONTEXT="$(dirname "${BASH_SOURCE[0]}")"
#declare -rx GMON_PREFIX="${CONTEXT}/.profile" # this doesn't seem to be working...

if [[ "$@" =~ '--clang' ]]
then
    readonly COMPILER='clang++ -target x86_64-w64-mingw64 -fcolor-diagnostics -fansi-escape-codes -ferror-limit=4'
else
    # Use g++ by default.
    readonly COMPILER='g++ -fdiagnostics-color=always -fmax-errors=4'
fi

declare OPTS=''
if [[ "$@" =~ '-p'|'--profile' ]]
then
    echo -e '\nbuilding with profiling support.'
    OPTS+=" -pg -fprofile-generate"
elif [[ "$@" =~ '-P'|'--profile-use' ]]
then
    echo -e '\nusing last generated profiling data.'
    OPTS+=" -fprofile-use"
fi

declare -r SHORTEN_STDLIB_PATH='s/C:\\mingw64\\x86_64-8.1.0-posix-seh\\lib\\gcc\\x86_64-w64-mingw32\\8.1.0\\include/\\STDLIB/g'

${COMPILER} -Wall -O3 ${OPTS} -time -fprofile-dir="${CONTEXT}/.profile" main.cpp -o main.exe |& sed ${SHORTEN_STDLIB_PATH}
