#!/bin/sh
# I apologize for committing the platform-specific sed filter.
# I want to keep this script in the repo so please bear with it
# as a viewer and fellow programmer :)
set -e
#readonly COMPILER='clang++ -target x86_64-w64-mingw64 -fcolor-diagnostics -fansi-escape-codes -ferror-limit=4'
readonly COMPILER='g++ -fdiagnostics-color=always -fmax-errors=4'
$COMPILER -O3 -Wall "$@" main.cpp -o main.exe |& sed 's/C:\\mingw64\\x86_64-8.1.0-posix-seh\\lib\\gcc\\x86_64-w64-mingw32\\8.1.0\\include/\\STDLIB/g'
