#!/bin/sh
#
# Personal notes:
# https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
set -e
readonly CONTEXT="$(dirname "${BASH_SOURCE[0]}")"
#declare -rx GMON_PREFIX="${CONTEXT}/.profile" # this doesn't seem to be working...

if [[ "$@" =~ '--clang' ]]
then
    readonly COMPILER='clang++ -target x86_64-w64-mingw64 -fcolor-diagnostics -fansi-escape-codes -ferror-limit=5'
else
    # Use g++ by default.
    readonly COMPILER='g++ -std=c++17 -fdiagnostics-color=always -fmax-errors=5'
fi

declare OPTS=''
if [[ "$@" =~ '-p'|'--profile' ]]
then
    echo -e '\nbuilding with profiling support.'
    OPTS+=" -pg -fprofile-generate"
elif [[ "$@" =~ '-P'|'--profile-use' ]]
then
    echo -e '\nusing last generated profiling data.'
    OPTS+=" -fprofile-use"
fi

declare -r SHORTEN_STDLIB_PATH='s/.:\/[^\n]+?\/include/\[1;35mSTDLIB\[39m/g'

${COMPILER}\
    -Wall -O3 ${OPTS}\
    -fprofile-dir="${CONTEXT}/.profile"\
    main.cpp -o main.exe\
    |& sed -E ${SHORTEN_STDLIB_PATH}
